### ISSUE TITLE
IBIM i developerWorks "Home Page" - need links to existing content

### ISSUE THREAD

**Issue by DawnMay** [IBM/developer#12]
The IBM i developerWorks "home page" - bookmarked at https://www.ibm.com/developerworks/ibmi/ is now completely useless.  It redirects to https://developer.ibm.com/components/ibm-i/, but that landing page does not have links to the existing content I previously could get to.  

The links in the left column are useless - there is no content for those categories.  There are no links to the existing content that I could previously get to from the main landing page.  This is a HUGE issue.  I do consulting work and have been telling all my clients to start with the IBM i developerWorks page.   Now I have to tell them to do an Internet search???

Now, you must either have book-marked existing pages, or know the appropriate internet search to fine the content.  This information MUST be linked from the main IBM i page. 

Dawn May
Dawn May Consulting, LLC
DawnMayiCan@outlook.com

**Comment by LinzSTP** [comment]
@DawnMay Hi Dawn, I understand your frustration, and have been working with Scott Forstie to come up with a solution to address the issues you've mentioned here (others have expressed similar concerns).  A couple of the more immediate actions we're taking include:

- Customizing the IBM i landing page https://developer.ibm.com/components/ibm-i/. In particular I'll add links to critical communities and resources in the  "More" section of the left navigation column. < Scott is currently reviewing the links that were on the old pages to determine which to add. We've added 2 new articles since launch and will be migrating several more (see bullet below)
- Updating then migrating this dW article https://www.ibm.com/developerworks/ibmi/library/i-newtoibmi/index.html and adding a new section called, ""How do I find more information, get code, and connect with the community" (or something similar). When it's on Developer,  I'll make this a permanently highlighted piece of content on the customized component page.
- Migrating +/- 10 additional dW articles to the new site, vetted by Scott and others from the IBM i team. The non-migrated IBM i content can be found here> 
https://www.ibm.com/developerworks/ibmi/library/. I have included this link in the More section of the landing page mentioned above.

The issue with the "useless" links in the left columns has been forwarded on to the architecture team. I think we can all agree that if there is no content of a particular type (blog, event, etc) then there should not be a link to a blank page from the landing page. 

We do have several additional solutions we're investigating to address the issue of not having the IBM i hub page on developerWorks anymore. Please contact me directly at lhalkire@us.ibm.com if you're interested in providing your input. I'd like to hear from you.

Thanks,
Linda Alkire, IBM Systems content manager

**Comment by DawnMay** [comment]
Hi Linda,

Thank you for contacting me on this.  The IBM i landing page is already much better since my last visit (although the Documentation link takes you to z information, not i).
When the links to empty content are removed, that will also be a really good change.

It’s good these improvements are starting to happen - with both COMMON and Power Systems TechU next week, it’s good to have the main landing page at least somewhat functional.
If clients express their concerns to me, I”ll let them know IBM is working on it….

And yes, I would be happy to provide my input on other solutions you are investigating.


There was also some additional information that one could access from the IBM i landing page - the IBM i Wiki and user group information.  I had also created a “Blog of Blogs” that summarizes my ‘I Can’ blog articles.
I have bookmarks to these pages (thankfully!) - and you can see in the following screen capture the left-navigation hierarchy for these pages.  I think this information is still valuable.
[cid:5150CFD9-EE7F-4C66-ACE7-EBCEAAE15C7A@hsd1.nh.comcast.net.]


Dawn May
dawnmayican@outlook.com<mailto:dawnmayican@outlook.com>
Dawn May Consulting, LLC

On Oct 9, 2018, at 4:08 PM, LinzSTP <notifications@github.com<mailto:notifications@github.com>> wrote:


@DawnMay<https://github.com/DawnMay> Hi Dawn, I understand your frustration, and have been working with Scott Forstie to come up with a solution to address the issues you've mention here (others have expressed similar concerns). A couple of the more immediate actions we're taking include:

  *   Customizing the IBM i landing page https://developer.ibm.com/components/ibm-i/. In particular I'll add links to critical communities and resources in the "More" section of the left navigation column. < Scott is currently reviewing the links that were on the old pages to determine which to add. We've added 2 new articles since launch and will be migrating several more (see bullet below)
  *   Updating then migrating this dW article https://www.ibm.com/developerworks/ibmi/library/i-newtoibmi/index.html and adding a new section called, ""How do I find more information, get code, and connect with the community" (or something similar). When it's on Developer, I'll make this a permanently highlighted piece of content on the customized component page.
  *   Migrating +/- 10 additional dW articles to the new site, vetted by Scott and others from the IBM i team. The non-migrated IBM i content can be found here>
https://www.ibm.com/developerworks/ibmi/library/. I have included this link in the More section of the landing page mentioned above.

The issue with the "useless" links in the left columns has been forwarded on to the architecture team. I think we can all agree that if there is no content of a particular type (blog, event, etc) then there should not be a link to a blank page from the landing page.

We do have several additional solutions we're investigating to address the issue of not having the IBM i hub page on developerWorks anymore. Please contact me directly at lhalkire@us.ibm.com<mailto:lhalkire@us.ibm.com> if you're interested in providing your input. I'd like to hear from you.

Thanks,
Linda Alkire, IBM Systems content manager
