### ISSUE TITLE
Finding Older Developer Works Articles?

### ISSUE THREAD

**Issue by drankinatty** [IBM/developer#15]
IBMDW folks, I have been a member for more than a decade. In the past it was a simple matter to navigate the site and find content within developerworks. Unfortunately, as time has gone by, developerworks and grown from a simple and useful resource, to a bewildering menagerie of sliding content, impossible navigation and searches that return nothing. For instance tonight I was looking for "Creating KParts Component" by David Faure that was located at http://www-106.ibm.com/developerworks/linux/edu/l-dw-linuxkp1-i.html, but is now nowhere to be found.

A lot has changed since 2008, but finding content should become easier, not harder. How can I locate past articles on developerworks now?

**Comment by DawnMay** [comment]
Hi David, 
I share your concern.  I have many saved bookmarks where the links are now dead.  I have discovered that IBM has done "housekeeping" on developerWorks content and appears to have randomly removed what is perceived to be old content. 
What they don't seem to understand is the date itself is not a good indicator of whether content is valid or not.  A lot of information is important, but doesn't change; some articles written in 2009 are as relevant today as they were 9 years ago.  Rather than delete content, developerWorks should verify the content first, and only remove information that is obsolete.  Of course, that is a harder project and it's just easier to delete things.  
Some of the wiki pages are gone too - some needed to be dealt with because of dated content, but some valuable content just disappeared. 
I have used Wayback Machine to find some very important information that appears to have disappeared.
Dawn

**Comment by neilmack** [comment]
Thank you for your comments. As you have observed, we are in the process of sorting, assessing, and in some cases, retiring content that has been published on developerWorks over the past several years. As you can no doubt appreciate, this is a major undertaking -- the site has now evolved to become "IBM Developer," and is designed to engage with and meet the needs of the modern development community.

Part of that evolution means assessing our older content for accuracy, relevance, and amount of traffic. We use that information to determine what's most useful to the current community. Although the particular page in question was retired some time ago, we recognize that occasionally there will be cases like this where people want to refer to older, less frequently accessed documents. We do regret the inconvenience when they are no longer available, and we will continue to assess our content archive and retirement processes, and available resources, including the possibility of a "live archive" for all retired content. Our goal is always to make sure we're serving our community as best we can. 

We hope you'll continue to visit IBM Developer and provide your thoughts. Modernizing a site like IBM Developer is a massive job; there will be bumps along the way. We welcome and appreciate your feedback, even when it's critical. We will keep working hard to provide a vibrant and useful resource for you and the entire development community.

**Comment by drankinatty** [comment]
Remember, much of the older content (especially Linux, C, SQL, PHP, etc..) is still very relevant  as the APIs have not significantly changed. What I have noticed is your newer content ignore the basics of each topic instead focusing on the latest niche addition to many of the topics you cover. Retiring the content that actually provides the fundamentals of each would be a grave mistake. If there is one company on earth that should be competent to index and preserve content, it's IBM. It would be a shame to see IBMDW not live up to its promise.
