### ISSUE TITLE
Process to get permission to create posts

### ISSUE THREAD

**Issue by nhaustein** [IBM/developer#151]
Hi, 
my organization uses developerWorks today to blog IBM storage related news. Since developerWorks will be sunset, we are looking for a new platform for our blogs. 

What is the process to get 6-8 people permission to create blogs on developer.ibm?
Can we have / create a category for our organization, the European Storage Competence Center?

Thanks.

**Comment by LindaMeyer** [comment]
Hi @nhaustein 
developerWorks isn't being sunset. For clarification developerWorks has been rebranded as IBM Developer. With that change, we are also changing how and where we publish content. The only thing that will be sunset at the end of the year is the old developerWorks community platform. 

We are shutting down the IBM developerWorks Connections Community pages. These are pages that contain (developerworks/community/) in the url. Community content now belongs on IBM Community (https://www.ibm.com/community/).

Since this is an internal issue, I'll reach out to you via email so we can discuss in detail.

**Comment by nhaustein** [comment]
thanks Linda, let us continue the discussion internally.
