### ISSUE TITLE
lost developerworks articles - broken links for all my developerworks articles.

### ISSUE THREAD

**Issue by santhoshkotte** [IBM/developer#199]
Hi IBM team
I have published three articles in the past related to IBM InfoSphere Information Server DataStage while working for the IBM India Software Lab. All of my articles are no longer available and it would be great if they can be activated again since they are very useful for the DataStage community. Here are the links when they used to be active
1. “Use DataStage Web Services Pack to fetch Lotus Notes data into InfoSphere Information Server DataStage module”.
http://www.ibm.com/developerworks/data/library/techarticle/dm-0912dominoappsinfosphere/ 

2.“Handling Complex Web Services in InfoSphere Information Server through DataStage ASB Packs v2”.
http://www.ibm.com/developerworks/library/ws-complexws/

3.“Extract data from Excel sources in IBM InfoSphere Information Server using DataStage Java Integration Stage”.
http://www.ibm.com/developerworks/data/library/techarticle/dm-1305handling/

Please help with reviving these.

**Comment by mcorbin-ibm** [comment]
[**_From our FAQ on IBM Developer:  What happened to developerWorks?_**](https://developer.ibm.com/feedback/)

IBM Developer was built from two legacy sites: IBM developerWorks and IBM Code.  IBM developerWorks' mission covered both open source technologies and IBM products.  IBM Code provided code patterns that helped developers solve specific problems or get started with new technologies and cloud services.

In 2018, IBM Developer was launched as IBM's developer resource site focusing on open source, cloud-based technologies and services.  Relevant content from IBM developerWorks was merged with IBM Code and the resulting content collection was rebranded as IBM Developer.

In 2021, we sunset the IBM developerWorks site to focus completely on the IBM Developer mission.

-----

I looked on the Internet archive to see if these articles could be found there, but unfortunately, they do not.  If you still have the text for them, you can see about publishing them on other content portals (like community.ibm.com) since they were not chosen to be migrated over to the new IBM Developer site.  

Please post any further comments or questions to our internal slack channel #ibmdeveloper
