### ISSUE TITLE
DeveloperWorks items not found

### ISSUE THREAD

**Issue by mbolla-ibm** [IBM/developer#2]
Trying to get DeveloperWorks content and keeps going to Developer.  Search doesn't find the IBM i QSYS2 tables to give me the details to use them.

**Comment by LinzSTP** [comment]
@mbolla-ibm what link were you trying to go to?

**Comment by mbolla-ibm** [comment]
https://www.ibm.com/developerworks/
Is the link I tried which went to https://developer.ibm.com/

Then it does not find the previous documentation:



I used to get things like this:
https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/IBM%20i%20Technology%20Updates/page/DISPLAY_JOURNAL%20%28easier%20searches%20of%20Audit%20Journal%29

Members

You are in:  IBM i Technology Updates >ý IBM i Technology Updates >ý DB2
for i - Technology Updates >ý DB2 for i - Services >ý DISPLAY_JOURNAL
(easier searches of Audit Journal)



DISPLAY_JOURNAL (easier searches of Audit Journal)



Clicking on this complete link did find that documentation.  Search
wouldn't let me look for anything else.


                                             
 Regards,                                    
                                             
 Mark Bolla                                  
 Application Developer                       
 Client Service Professional @ IBM Client    
 Innovation Center Lansing                   
                                             
                                               
                                               
                                               
 Phone: 248-552-5774 | Mobile:                 
 216-502-6601                                  
 E-mail: mtbolla@us.ibm.com         18000 West 
                                     Nine Mile 
                                          Road 
                                   Southfield, 
                                      MI 48075 
                                        United 
                                        States 
                                               







From:	LinzSTP <notifications@github.com>
To:	IBM/developer <developer@noreply.github.com>
Cc:	mbolla-ibm <mtbolla@us.ibm.com>, Mention
            <mention@noreply.github.com>
Date:	09/11/2018 11:46 AM
Subject:	Re: [IBM/developer] DeveloperWorks items not found (#2)



@mbolla-ibm what link were you trying to go to?


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by LinzSTP** [comment]
@mbolla-ibm  Hi Mark, developerWorks is actually evolving to become "IBM Developer." It's a new approach that will provide developers with code, processes, and insight -- everything you need to do your job better. As we complete this major evolution, we're migrating a lot of content over to our new home, and we'll be archiving some older pages that are still being used but which aren't completely current. (For the background, see this post from VP Angel Diaz: https://developer.ibm.com/blogs/2018/08/30/welcome-ibm-developer/ . You can also check the FAQs on this page: https://developer.ibm.com/feedback/ )

As you've already noticed, there will be some changes and re-directs, and some links won't be where you're used to finding them. The IBM Community wiki that you've linked to above is still in place; it and other wikis can be accessed starting at the wiki home page: https://www.ibm.com/developerworks/community/wikis/home.  All the legacy content from developerWorks is still available via external search engines. We'll do our best to ensure that you can still find the content you need, and we hope you'll find the new IBM Developer to be a valuable resource.

Thanks!
Linda

**Comment by DawnMay** [comment]
The IBM i  developerWorks landing page that is gone was widely shared in the IBM i community as the starting point for much documentation.  The loss of this page is making IBM look very bad - while the content may all be there, the organization around it that https://www.ibm.com/developerworks/ibmi/ provided is gone.  In fact, the content at that link is useless to an IBM i client.  

I opened an issue specifically on this also - 
https://github.com/IBM/developer/issues/12.

This is an example of content that you just cannot take away - clients depend upon this information.  Please find a way to get that IBM i landing page back.

I am a former IBMer who has several articles that were written and previously published under the IBM i articles, and those are now gone from the list of articles that is displayed.  Just because technical documentation was written in 2015, doesn't mean it is obsolete today.  Much of this important information is lasting. 

This change is a major disappointment.

Dawn
