### ISSUE TITLE
Problem Blockchain Credits

### ISSUE THREAD

**Issue by javporris** [IBM/developer#38]
Good afternoon,

I want to test your "Blockchain Platform" product. I'm on this link https://www.ibm.com/blockchain/platform, I clic on "Get Started now" button, I've register my user, but on the step when you ask my the information of my company and explain the 500$ of credit to test the platform, I can't send the information, every time that I clic on "Complete registration" button, you refresh the page without errors...

I need to test the blockchain platform for a new project, is important to my company. If you tell me an e-mail a can tell you my IBMid.

Thanks for your help.

**Comment by neilmack** [comment]
Thank you very much for your note. While this repository is designed for feedback on IBM Developer content (https://developer.ibm.com), we'll try to find you the right support forum where you can get assistance. More shortly.

**Comment by javporris** [comment]
Thank you, the truth is that I have already tried by all possible ways but nobody gives me an answer.

**Comment by neilmack** [comment]
I completely understand -- I'll do my best to find someone who can help. I'll let you know as soon as I get a response. Thanks very much for your patience!

**Comment by alroads** [comment]
Hi there. I am with the IBM Partnership and Ecosystem team. My apologies that you experienced issues with the offering form. When signing up the for the IBM Blockchain Starter pla , on the [first form](https://www.ibm.com/account/reg/us-en/signup?formid=urx-32798) you are presented, please select **"United States"** and please a company email domain (no gmail for example). However, on the **second form, please make sure you provide your accurate address (Country, etc.).** After you complete the forms using this guidance,  please share with me the email you used so that our team can look out for your application. If you don't want to share your email here, please email at alroads@us.ibm.com

**Comment by neilmack** [comment]
Contacted by blockchain team and resolved.
